service: aws-instance-up
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128

functions:
  cronHandler:
    handler: index.run
    events:
#      cron(Minutes Hours Day-of-month Month Day-of-week Year)
      - schedule: cron(55 * ? * MON-FRI *)
